#include "std_msgs/msg/Header.idl"

module cg_msgs {
  module msg {
    struct Slip {
      std_msgs::msg::Header header;

      // Slip percentage
      @default (value = 0.0)
      float slip;
      float vel_int;
      float vel_twst;
      float vel_avg;


    };
  };
};
