#include "std_msgs/msg/Header.idl"

module cg_msgs {
  module msg {
    struct Slip {
      std_msgs::msg::Header header;

      // Instantaneous slip percentage, in [0,1]
      @default (value = 0.0)
      float slip;

      // Averaged slip percentage, also in [0,1]
      @default (value = 0.0)
      float slip_avg;

      // Flag if in a slip case or not
      @default (value = true)
      boolean slip_latch;

      // Instantaneous vehicle velocity estimate [m/s]
      @default (value = 0.0)
      float vel;

      // Averaged vehicle velocity estimate [m/s]
      @default (value = 0.0)
      float vel_avg;

    };
  };
};
