#include "std_msgs/msg/Header.idl"

module cg_msgs {
  module msg {
    struct EncoderTelemetry {
      std_msgs::msg::Header header;

      // Slip percentage
      @default (value = 0)
      float slip;


    };
  };
};
