bearing_node:
  ros__parameters:
    # Positions relative to worksite frame (bottom left of map)
    tags: 
      position: # m
        x: ['3.49563', '6.939225', '3.44706', '0.02744']
        y: ['7.279027', '3.562075', '-0.00215', '3.6699']
        z: ['0.74825', '0.80415', '0.80195', '0.76385']
      orientation: # rad
        x: ['1.6421','-1.5953','-1.5725','0.2308']
        y: ['0.0','-1.5349','0.0204','1.5695']
        z: ['0.0','1.5593','-0.0204','0.2305']
    # Camera position relative to the robot base frame
    base_cam_tf:
      position: # m
        x: '0.2257'
        y: '0'
        z: '0.5269'
      orientation: # rad
        x: '-1.5708'
        y: '0'
        z: '-1.5708'
    # Confidence in bearing estimate (lower is higher confidence)
    bearing_covariance: 0.005
    # Time before transform is discarded / not considered in calculation
    tf_discard_time: 0.8
    # Buffer for calculating average angle
    rolling_avg_buffer: 5
    # Frequency of angle publishing
    pub_freq: 10
