bearing_node:
  ros__parameters:
    # Confidence in bearing estimate (lower is higher confidence)
    bearing_covariance: 0.005
    # Time before transform is discarded / not considered in calculation
    tf_discard_time: 0.8
    # Frequency of angle publishing
    pub_freq: 10
