bearing_node:
  ros__parameters:
    # Camera position relative to the robot base frame
    base_cam_tf:
      position: # m
        x: '0.2257'
        y: '0'
        z: '0.5269'
      orientation: # rad
        x: '-1.5708'
        y: '0'
        z: '-1.5708'
    # Confidence in bearing estimate (lower is higher confidence)
    bearing_covariance: 0.005
    # Time before transform is discarded / not considered in calculation
    tf_discard_time: 0.8
    # Frequency of angle publishing
    pub_freq: 10
