version: "3.9"
services:
  cg-dev:
    build:
      context: ./
      dockerfile: ./docker/cgdev.dockerfile
      network: host
    devices:
      - /dev/input/:/dev/input/
    privileged: true
    volumes:
      - .:/root/CRATER_GRADER
      - /dev/:/dev/
    ports:
      - 5901:5900 # <external port>:<container port>
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  cg-dev-ros1:
    build:
      context: ./
      dockerfile: ./docker/cgdev_ros1.dockerfile
      network: host
    devices:
      - /dev/input/:/dev/input/
    privileged: true
    volumes:
      - .:/root/CRATER_GRADER
      - /dev/:/dev/
    ports:
      - 5901:5900 # <external port>:<container port>
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
