version: "3.9"
services:
  cg-dev:
    image: p84514faf325/cratergrader:cg-460-v1.2.1
    devices:
      - /dev/input/:/dev/input/
    volumes:
      - .:/root/CRATER_GRADER
    ports:
      - 5900:5900 # <external port>:<container port>
      - 9090:9090 # Websocket for health monitoring via rosbridge_suite
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  cg-dev-addon:
    build:
      context: ./
      dockerfile: ./docker/addon.dockerfile
      network: host
    volumes:
      - .:/root/CRATER_GRADER
    ports:
      - 5900:5900 # <external port>:<container port>
      - 9090:9090 # Websocket for health monitoring via rosbridge_suite
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  cg-dev-hw:
    image: p84514faf325/cratergrader:cg-460-v1.2.1
    privileged: true
    network_mode: "host"
    volumes:
      - .:/root/CRATER_GRADER
      - /dev/:/dev/
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  cg-dev-full-build:
    build:
      context: ./
      dockerfile: ./docker/cgdev.dockerfile
      network: host
    volumes:
      - .:/root/CRATER_GRADER
    ports:
      - 5900:5900 # <external port>:<container port>
      - 9090:9090 # Websocket for health monitoring via rosbridge_suite
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
