version: "3.9"
services:
  cg-dev:
    build:
      context: ./
      dockerfile: ./docker/cgdev.dockerfile
      network: host
    devices:
      - /dev/input/:/dev/input/
      # - /dev/video0:/dev/video0
      # - /dev/video1:/dev/video1
      # - /dev/video2:/dev/video2
    privileged: true
    volumes:
      - .:/root/CRATER_GRADER
      - /dev/:/dev/
    ports:
      - 5901:5900 # <external port>:<container port>
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
