version: "3.9"
services:
  cg-dev:
    build:
      context: ./
      dockerfile: ./docker/cgdev.dockerfile
      network: host
    devices:
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
    volumes:  
      - .:/root/CRATER_GRADER
    ports:
      - 5901:5900 # <external port>:<container port>
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  cg-dev-hw:
    build:
      context: ./
      dockerfile: ./docker/cgdev.dockerfile
      network: host
    privileged: true
    volumes:
      - .:/root/CRATER_GRADER
      - /dev/:/dev/
    ports:
      - 5901:5900 # <external port>:<container port>
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
