version: "3.9"
services:
  cg-dev:
    build:
      context: ./
      dockerfile: ./docker/cg_dev.dockerfile
    volumes:
      - .:/root/CRATER_GRADER
      - ~/.ssh/:/root/.ssh/ # May be non-functioning in windows
      - ~/.gitconfig:/root/.gitconfig # May be non-functioning in windows
    tty: true # use terminal, i.e. -t flag
    stdin_open: true # allow terminal input, i.e. -i flag
