channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - pip:
    - opencv-python
    - catkin_pkg
    - empy
    - lark
    - pyyaml
    - netifaces
    - pymongo
