beacon_static_transform_publisher:
  ros__parameters:
    beacon_back:
      x: '-0.385'
      y: '0.060'
      z: '0.050'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: uwb_tag_0
    beacon_front:
      x: '0.177'
      y: '0'
      z: '0.377'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: uwb_tag_1
