beacon_static_transform_publisher:
  ros__parameters:
    beacon_back:
      x: '-0.48761'
      y: '-0.0'
      z: '0.0695'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: uwb_tag_0
    beacon_front:
      x: '0.2192'
      y: '-0.0178'
      z: '0.2505'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: uwb_tag_1
