uwb_beacon_rtls_node:
  ros__parameters:
    beacon_port: '/dev/cg_dev/tty_uwb1'
    beacon_verbose: True
    positional_rms: 0.012
    beacon_hz: 10
    publish_raw_tags: True
    raw_topic: '/uwb_beacon/raw_tags/'
    fused_pose_topic: '/uwb_beacon/fused_pose'
