uwb_beacon_rtls_node:
  ros__parameters:
    beacon_port: '/dev/cg_dev/tty_uwb1'
    beacon_verbose: False
    positional_rms: 0.012
    publish_raw_tags: False
    publish_ekf_tags: False
    raw_topic: '/uwb_beacon/raw_tags'
    ekf_topic: '/uwb_beacon/ekf_tags'
    fused_pose_topic: '/uwb_beacon/fused_pose'