worksystem_control_node:
  ros__parameters:
    longitudinal_velocity_kp: 1.0
    longitudinal_velocity_ki: 0.0
    longitudinal_velocity_kd: 0.5
    steer_speed_filter_window_size: 10
    cmd_msg_filter_window_size: 10
    max_wheel_velocity_delta: 10.0 # %FS 

    lateral_stanley_gain: 2.5
    lateral_stanley_softening_constant: 0.0 # unused
    lateral_heading_gain: 1.5
    min_drive_speed_scalar: 0.0
    max_steer_speed: 500.0
    lookahead_heading_offset: 5
