worksystem_control_node:
  ros__parameters:
    longitudinal_velocity_kp: 1.0
    longitudinal_velocity_ki: 0.0
    longitudinal_velocity_kd: 0.5
    steer_speed_filter_window_size: 10
    cmd_msg_filter_window_size: 10
    steer_error_filter_window_size: 10

    lateral_stanley_gain: 2.0
    lateral_stanley_softening_constant: 0.0 # unused
    lateral_heading_gain: 0.0
    min_drive_speed_scalar: 0.0

    max_steer_error: 50.0
    steer_full_scale: 2800.0