worksystem_control_node:
  ros__parameters:
    longitudinal_velocity_kp: 1.0
    longitudinal_velocity_ki: 0.0
    longitudinal_velocity_kd: 0.5
    steer_speed_filter_window_size: 10

    lateral_stanley_gain: 1.8
    lateral_stanley_softening_constant: 0.0 # unused
    min_drive_speed_scalar: 0.0
