worksystem_control_node:
  ros__parameters:

    # State Specific Control Parameters

    # Exploration State Parameters
    exploration_state:
      longitudinal_velocity_kp: 1.0
      longitudinal_velocity_ki: 0.0
      longitudinal_velocity_kd: 0.5
      steer_speed_filter_window_size: 5
      # Stanley Controller Parameters
      lateral_stanley_gain: 1.3
      lateral_stanley_softening_constant: 0.0 # unused

    # Transport State Parameters:
    transport_state:
      longitudinal_velocity_kp: 1.0
      longitudinal_velocity_ki: 0.0
      longitudinal_velocity_kd: 0.5
      steer_speed_filter_window_size: 5
      # Stanley Controller Parameters
      lateral_stanley_gain: 1.3
      lateral_stanley_softening_constant: 0.0 # unused
