total_station_beacon_static_transform_publisher:
  ros__parameters:
    total_station_prism:
      x: '-0.48761'
      y: '-0.0'
      z: '0.0695'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: total_station_prism