total_station_beacon_static_transform_publisher:
  ros__parameters:
    ts_prism_x_offset: '6.9098' # meters
    ts_prism_y_offset: '4.8026' # meters
    ts_prism_z_offset: '2.17185' # meters
    ts_prism_z_rotation: '-0.005047857' #radians
    total_station_prism:
      x: '0.0'
      y: '0.1'
      z: '0.8'
      roll: '0'
      pitch: '0'
      yaw: '0'
      parent_frame_id: base_link
      child_frame_id: total_station_prism
