total_station_node:
  ros__parameters:
    total_station_port: '/dev/ttyUSB0'
    total_station_verbose: True
    positional_rms: 0.005
    total_station_hz: 10
    raw_topic: '/total_station/'
    ts_prism_x_offset: 6.922135 # meters
    ts_prism_y_offset: 2.366758 # meters
    ts_prism_z_offset: 2.193417 # meters
    ts_prism_z_rotation: 0.0 #-0.005047857 #radians
