/**:
  ros__parameters:
    video_device: "/dev/cg_dev/sun_cam"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv"
    image_width: 1920
    image_height: 1280
    camera_name: "camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
