autograder_node:
  ros__parameters:
      # Blade heights for design plane and raised height, on [0.0, 100.0] where 0:= highest possible blade position (closest to chassis) and 100 := lowest possible blade position (furthest from chassis)
      design_blade_pos: 80.0 # Keep blade at this height when driving normally
      raised_blade_pos: 0.0 # Raise blade to this height when reversing
