realsense_static_transform_publisher:
  ros__parameters:
    x: '0.25565'
    y: '0.01745'
    z: '0.38277'
    roll: '-1.867'
    pitch: '0.0'
    yaw: '-1.5708'
    parent_frame_id: base_link
    child_frame_id: realsense_frame
