realsense_static_transform_publisher:
  ros__parameters:
    x: '0.24734'
    y: '0.018'
    z: '0.57861'
    roll: '-2.300231269'
    pitch: '-0.015343837'
    yaw: '-1.5952951'
    parent_frame_id: 'base_link'
    child_frame_id: 'realsense_frame'
