@startuml
colors
@enduml

@startuml PlanningFSM_20221015_REV02
mainframe PlanningFSM_20221015_REV02
' Formatting
' ------------------------------------
hide empty description

' State blocks
skinparam state {
  BackgroundColor #DeepSkyBlue
}

' choice blocks
<style>
  diamond {
    BackgroundColor #Tomato
}
</style>


' States and Interactions
' ------------------------------------
' Global states
state EndMission
state PlanExploration #MediumSpringGreen
state PlanTransport #MediumPurple
state UpdateMap
  UpdateMap : Request site_map_server
state GetExplorationGoals #MediumSpringGreen
  GetExplorationGoals : Select N goals
state GetTransportGoals #MediumPurple
  GetTransportGoals : Select 3 goals: src, sink, src
state MapExplored <<choice>>
  note right of MapExplored
    MapExplored?
  end note
state SiteWorkDone <<choice>>
  note right of SiteWorkDone
    SiteWorkDone?
  end note
state ReplanTransport <<choice>>
  note right of ReplanTransport
    ReplanTransport?
  end note

' Fallback states
state FallBack #Gainsboro {
  state CallForHelp #Gainsboro 
  state OperatorIntervention #Gainsboro 
  state OperatorAvailable <<choice>>
    note right of OperatorAvailable
    OperatorAvailable?
    end note
  state ContinueMission <<choice>>
    note right of ContinueMission
      ContinueMission?
    end note

  ' Fallback state interactions
  CallForHelp --> OperatorAvailable : call_help
  OperatorAvailable --> OperatorIntervention : yes
    OperatorIntervention --> ContinueMission : check_mission
      ContinueMission --> UpdateMap : yes
      ContinueMission --> EndMission : no
  OperatorAvailable --> EndMission : no
}

' Driving states
state FollowingTrajectory #Magenta
state EscapeManeuver #Magenta
state GetWorksystemTrajectory #Magenta
  GetWorksystemTrajectory : Call Kinematic, Velocity, Tool planners
state GoalsRemaining <<choice>>
  note right of GoalsRemaining
    GoalsRemaining?
  end note

' Driving state interactions
GoalsRemaining --> GetWorksystemTrajectory : yes
  GetWorksystemTrajectory --> FollowingTrajectory : follow_trajectory
    FollowingTrajectory --> GoalsRemaining : goal_reached
    FollowingTrajectory --> EscapeManeuver : stuck
      EscapeManeuver --> FollowingTrajectory : not_stuck
      EscapeManeuver -->  CallForHelp : abort
GoalsRemaining --> UpdateMap : no

' Global state interactions
[*] --> UpdateMap : start
  UpdateMap --> SiteWorkDone : map_updated
  SiteWorkDone --> EndMission : yes
  SiteWorkDone --> MapExplored : no
    MapExplored --> ReplanTransport : yes
      ReplanTransport --> PlanTransport : yes
        PlanTransport --> GetTransportGoals : transport_planned
      ReplanTransport --> GetTransportGoals : no
        GetTransportGoals --> GoalsRemaining : drive
    MapExplored --> PlanExploration : no
      PlanExploration --> GetExplorationGoals : exploration_planned
      GetExplorationGoals --> GoalsRemaining : drive
EndMission --> [*] : stop

@enduml

