@startuml
colors
@enduml

@startuml PlanningFSM_20221103_REV05
mainframe PlanningFSM_20221103_REV05
' Formatting
' ------------------------------------
hide empty description

' State blocks
skinparam state {
  BackgroundColor #DeepSkyBlue
}

' choice blocks
<style>
  diamond {
    BackgroundColor #Tomato
}
</style>


' States and Interactions
' ------------------------------------
' Global states
state EndMission_L0
state PlanExploration_L0 #MediumSpringGreen
state PlanTransport_L0 #MediumPurple
state UpdateMap_L0
  UpdateMap_L0 : Request site_map_server
state GetExplorationGoals_L0 #MediumSpringGreen
  GetExplorationGoals_L0 : Select N goals
state GetTransportGoals_L0 #MediumPurple
  GetTransportGoals_L0 : Select 3 goals: src, sink, src
state MapExplored_L0 <<choice>>
  note right of MapExplored_L0
    MapExplored_L0?
  end note
state SiteWorkDone_L0 <<choice>>
  note left of SiteWorkDone_L0
    SiteWorkDone_L0?
  end note
state RePlanTransport_L0 <<choice>>
  note right of RePlanTransport_L0
    RePlanTransport_L0?
  end note

' Fallback states
state FallBack_L1 #Gainsboro {
  state CallForHelp_L0 #Gainsboro 
  state OperatorIntervention_L0 #Gainsboro 
  state OperatorAvailable_L0 <<choice>>
    note right of OperatorAvailable_L0
    OperatorAvailable_L0?
    end note
  state ContinueMission_L0 <<choice>>
    note right of ContinueMission_L0
      ContinueMission_L0?
    end note

  ' Fallback state interactions
  CallForHelp_L0 -d-> OperatorAvailable_L0 : call_help
  OperatorAvailable_L0 -d-> OperatorIntervention_L0 : yes
    OperatorIntervention_L0 -d-> ContinueMission_L0 : check_mission
      ContinueMission_L0 -l-> UpdateMap_L0 : yes
      ContinueMission_L0 -d-> EndMission_L0 : no
  OperatorAvailable_L0 -d-> EndMission_L0 : no
}

' Driving states
state FollowingTrajectory_L0 #Magenta
state EscapeManeuver_L0 #Magenta
state GetWorksystemTrajectory_L0 #Magenta
  GetWorksystemTrajectory_L0 : Call Kinematic, Velocity, Tool planners
state GoalsRemaining_L0 <<choice>>
  note right of GoalsRemaining_L0
    GoalsRemaining_L0?
  end note

' Driving state interactions
GoalsRemaining_L0 -u-> GetWorksystemTrajectory_L0 : yes
  GetWorksystemTrajectory_L0 -u-> FollowingTrajectory_L0 : follow_trajectory
    FollowingTrajectory_L0 --> GoalsRemaining_L0 : goal_reached
    FollowingTrajectory_L0 --> GetWorksystemTrajectory_L0 : replan
    FollowingTrajectory_L0 --> EscapeManeuver_L0 : stuck
      EscapeManeuver_L0 -d-> FollowingTrajectory_L0 : not_stuck
      EscapeManeuver_L0 -r->  CallForHelp_L0 : abort
GoalsRemaining_L0 -d-> UpdateMap_L0 : no

' Global state interactions
[*] -d-> UpdateMap_L0 : start
  UpdateMap_L0 -d-> SiteWorkDone_L0 : map_updated
  SiteWorkDone_L0 -r-> EndMission_L0 : yes
  SiteWorkDone_L0 -l-> MapExplored_L0 : no
    MapExplored_L0 -d-> RePlanTransport_L0 : yes
      RePlanTransport_L0 -d-> PlanTransport_L0 : yes
        PlanTransport_L0 -d-> GetTransportGoals_L0 : transport_planned
      RePlanTransport_L0 -d-> GetTransportGoals_L0 : no
        GetTransportGoals_L0 -d-> GoalsRemaining_L0 : drive
    MapExplored_L0 -d-> PlanExploration_L0 : no
      PlanExploration_L0 -d-> GetExplorationGoals_L0 : exploration_planned
      GetExplorationGoals_L0 -d-> GoalsRemaining_L0 : drive
EndMission_L0 --> [*] : stop

@enduml

