apriltag:
  apriltag:
    ros__parameters:
      image_transport: raw # image format
      family: Standard41h12 # tag family name
      size: 0.383 # tag edge size in meter
      max_hamming: 0 # maximum allowed hamming distance (corrected bits)
      z_up: true # rotate about x-axis to have Z pointing upwards

      # see "apriltag.h" for more documentation on these optional parameters
      decimate: 1.0 # decimate resolution for quad detection
      blur: 0.0 # sigma of Gaussian blur for quad detection
      refine-edges: 1 # snap to strong gradients
      threads: 4 # number of threads
      refine-decode: 0 # increase the number of detected tags
      refine-pose: 1 # increase the accuracy of the extracted pose
      debug: 0 # write additional debugging images to current working directory

      tag_ids: [0, 1, 2, 3] # tag IDs for which to publish transform
