point_cloud_registration:
  ros__parameters:
    source_frame: realsense_frame
    target_frame: odom
    icp_max_iters: 50  # Max iterations for ICP
    voxel_filter_size: 0.01  # Voxel side length for downsampling [m]
