site_map:
  ros__parameters:
    # Map dimensions; UPDATE FOR BEHAVIORE EXECUTIVE BELOW
    # site assumed to be 5mx5m
    height: 50 # number of cells in col
    width: 50 # number cells in row
    resolution: 0.1 # meters
    xTransform: 1.0 # meters
    yTransform: 1.0 # meters

    # SiteMap specific params
    unseenGridHeight: 0.0 # meters, Kalman Filter seed
    incomingPointVariance: 0.05 # meters^2
    cellStartingVariance: 10.0 # meters^2
    minCellVariance: 0.01 # meters^2

behavior_executive_node:
  ros__parameters:
    # site assumed to be 5mx5m
    # Map dimensions; should match site_map dimensions!
    height: 50 # number of cells in col
    width: 50 # number cells in row
    resolution: 0.1 # meters
    xTransform: 1.0 # meters
    yTransform: 1.0 # meters
