site_map:
  ros__parameters:
    # Map dimensions; UPDATE FOR BEHAVIOR EXECUTIVE BELOW
    # site assumed to be 5mx5m
    height: 50 # number of cells in col
    width: 50 # number cells in row
    resolution: 0.1 # meters
    xTransform: 1.0 # meters
    yTransform: 1.0 # meters

    # SiteMap specific params
    unseenGridHeight: 0.0 # meters, Kalman Filter seed
    incomingPointVariance: 0.05 # meters^2
    cellStartingVariance: 1.0 # meters^2
    minCellVariance: 0.002 # meters^2
    oosThreshold: 0.03 # meters 

    # Loading from a map filepath
    static_map: true
    load_height_map_from_filepath: true
    #### "Obvious crater" maps
    load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/pipeline_transport.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/run01_exploration_20221119.csv" # use absolute path

    #### "Malformed crater" maps
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/russells_fun_map.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/half_auton_half_manual_exploration.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/map001.csv" # use absolute path --> same as half_auton_half_manual_exploration
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/full_exploration.csv" # use absolute path

    #### "Noisy" maps
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/max_map.csv" # use absolute path MORPHIN PRESENT
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/auton_transition.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/exploration_map_check_test.csv" # use absolute path
    
    #### "Extreme gouging" maps
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/normal_map.csv" # use absolute path

    #### "Partially unseen" maps
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/red_demo.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/nov_11_crater.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/donut_exploration.csv" # use absolute path
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/autonomous_mapping.csv" # use absolute path

    #### Other
    # load_height_map_filepath: "/root/CRATER_GRADER/cg_ws/src/mapping/saved_maps/cmu_craters_blurred_map.csv" # use absolute path

behavior_executive_node:
  ros__parameters:
    # site assumed to be 5mx5m
    # Map dimensions; should match site_map dimensions!
    height: 50 # number of cells in col
    width: 50 # number cells in row
    resolution: 0.1 # meters
    xTransform: 1.0 # meters
    yTransform: 1.0 # meters
